<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Alert;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends  EntityRepository
{
    /**
     * @param $id
     *
     * @return Alert
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAlertById($id) {
        $qb = $this->createQueryBuilder('alert');
        $qb
            ->andWhere('alert.id = :id')
            ->setParameter('id',$id)
        ;
        return $qb->getQuery()->getSingleResult();
    }
    /**
     * @param $email
     *
     * @return Alert
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAlertByUser(User $user) {
        $qb = $this->createQueryBuilder('alert');
        $qb
            ->andWhere('alert.user = :user')
            ->setParameter('user',$user)
        ;
        return $qb->getQuery()->getSingleResult();
    }

    /**
     *
     * @return Alert[]
     */
    public function getAlerts($city, $department, $country) {
        $qb = $this->createQueryBuilder('alert');
        $qb->innerJoin("alert.userCreator" , "user_creator");
        $qb->leftJoin("alert.userHelpAlerts" , "user_help_alerts");
        $qb->leftJoin("user_help_alerts.user" , "user_helping");

        $qb->addSelect("user_creator");
        $qb->addSelect("user_help_alerts");
        $qb->addSelect("user_helping");

        if(! is_null($city)) {
            $qb
                ->andWhere('alert.positionCity = :city')
                ->setParameter('city',$city);
        }
        if(! is_null($department)) {
            $qb
                ->andWhere('alert.positionDep = :dep')
                ->setParameter('dep',$department);
        }
        if(! is_null($country)) {
            $qb
                ->andWhere('alert.positionCountry = :country')
                ->setParameter('country',$country);
        }

        return $qb->getQuery()->getResult();
    }

//    private function filterByCityNotNull(QueryBuilder &$qb, $city) {
//        if(! is_null($city)) {
//            $qb
//                ->andWhere('alert.positionCity = :city')
//                ->setParameter('city',$city);
//        }
//    }
//
}
