<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Alert;
use AppBundle\Entity\User;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     *
     * @return Alert
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAlertById($id) {
        $qb = $this->createQueryBuilder('alert');
        $qb
            ->andWhere('alert.id = :id')
            ->setParameter('id',$id)
        ;
        return $qb->getQuery()->getSingleResult();
    }
    /**
     * @param $email
     *
     * @return Alert
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAlertByUser(User $user) {
        $qb = $this->createQueryBuilder('alert');
        $qb
            ->andWhere('alert.user = :user')
            ->setParameter('user',$user)
        ;
        return $qb->getQuery()->getSingleResult();
    }

    /**
     *
     * @return Alert[]
     */
    public function getAlerts() {
        $qb = $this->createQueryBuilder('alert');
//        $qb
//            ->andWhere('alert.id = :id')
//            ->setParameter('id',$id)
//            ;
        return $qb->getQuery()->getResult();
    }
}
