<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     *
     * @return User
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getUserById($id) {
        $qb = $this->createQueryBuilder('user');
        $qb
            ->addSelect('alerts')
            ->leftJoin('user.alerts', 'alerts')
            ->andWhere('user.id = :id')
            ->setParameter('id',$id)
            ;
        return $qb->getQuery()->getSingleResult();
    } /**
     * @param $email
     *
     * @return User
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getUserByEmail($email) {
        $qb = $this->createQueryBuilder('user');
        $qb
            ->andWhere('user.email = :email')
            ->setParameter('email',$email)
            ;
        return $qb->getQuery()->getSingleResult();
    }

    /**
     *
     * @return User[]
     */
    public function getUsers() {
        $qb = $this->createQueryBuilder('user');
//        $qb
//            ->andWhere('user.id = :id')
//            ->setParameter('id',$id)
//            ;
        return $qb->getQuery()->getResult();
    }
}
