services:
    repository.user:
        class: AppBundle\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['AppBundle:User']
    repository.alert:
        class: AppBundle\Repository\AlertRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['AppBundle:Alert']

    service.user:
        class: AppBundle\Services\CrudUserService
        arguments: ['@doctrine.orm.default_entity_manager']
    service.alert:
        class: AppBundle\Services\CrudAlertService
        arguments: ['@doctrine.orm.default_entity_manager']